# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js_pipeline_code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Testing:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm test
    - run: docker build . -t nogomerl/node-web-app
    - run: docker images -a
    
    - name: Log in to Docker Hub
      uses: docker/login-action@1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and push Docker image
      uses: docker/build-push-action@1
      with:
          context: .
          push: true
        
    #- run: docker run --name node-dru alpine sh
    #- run: docker container ls -a
    #- run: docker commit node-dru nogomerl/node-dru
    #- run: docker images -a
    #- run: docker login
    #- run: docker push nogomerl/node-web-app
    #- run: docker push nogomerl/node-dru
